variables:
  NODE_VERSION: '16'
  NODE_IMAGE: 'node:${NODE_VERSION}'

stages:
  - install
  - test
  - build
  - publish

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

deps:
  stage: install
  image: ${NODE_IMAGE}
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - npm audit
    - npm i

build:
  stage: build
  image: ${NODE_IMAGE}
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - npm run build

eslint:
  stage: test
  image: ${NODE_IMAGE}
  script:
    - npm run lint

unit-tests:
  stage: test
  image: ${NODE_IMAGE}
  script:
    - npm run test:unit:cov

npm:
  stage: publish
  image: ${NODE_IMAGE}
  only:
    - master
  script:
    - npx semantic-release