variables:
  NODE_VERSION: '15.11-alpine'
  NODE_IMAGE: 'node:${NODE_VERSION}'

stages:
  - install
  - test
  - build
  - publish

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

deps:
  stage: install
  image: ${NODE_IMAGE}
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - npm audit
    - npm ci

prettier:
  stage: test
  image: ${NODE_IMAGE}
  script:
    - npm run format:check

eslint:
  stage: test
  image: ${NODE_IMAGE}
  script:
    - npm run lint

unit-tests:
  stage: test
  image: ${NODE_IMAGE}
  script:
    - npm run test

build:
  stage: build
  image: ${NODE_IMAGE}
  artifacts:
    paths:
      - lib
    expire_in: 1 week
  script:
    - npm run build

npm:
  stage: publish
  image: ${NODE_IMAGE}
  only:
    - tags
  script:
    - echo ${NPM_TOKEN}
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm publish --access public